database:
  host: localhost
  port: 3306
  database: slyapi
  username: root
  password: password

messages:
  only-players: "&cEste comando só pode ser executado por jogadores!"
  no-permission: "&cVocê não tem permissão para executar este comando!"
  player-not-found: "&cJogador não encontrado!"
  invalid-amount: "&cQuantia inválida!"
  insufficient-funds: "&cFundos insuficientes!"
  
  clan-help:
    - "&6=== Sistema de Clans ==="
    - "&e/clan criar <nome> <tag> &7- Cria um clan"
    - "&e/clan deletar &7- Deleta seu clan"
    - "&e/clan convidar <jogador> &7- Convida um jogador"
    - "&e/clan sair &7- Sai do clan"
    - "&e/clan expulsar <jogador> &7- Expulsa um jogador"
    - "&e/clan info &7- Informações do clan"
    - "&e/clan membros &7- Lista membros"
    - "&e/clan depositar <quantia> &7- Deposita dinheiro"
    - "&e/clan sacar <quantia> &7- Saca dinheiro"
    - "&e/clan settag <tag> &7- Define tag do clan"
    - "&e/clan guerra <clan> &7- Declara guerra"
    - "&e/clan top &7- Top clans"
  
  clan-create-usage: "&cUso: /clan criar <nome> <tag>"
  clan-invite-usage: "&cUso: /clan convidar <jogador>"
  clan-kick-usage: "&cUso: /clan expulsar <jogador>"
  clan-deposit-usage: "&cUso: /clan depositar <quantia>"
  clan-withdraw-usage: "&cUso: /clan sacar <quantia>"
  clan-settag-usage: "&cUso: /clan settag <tag>"
  clan-war-usage: "&cUso: /clan guerra <clan>"
  
  already-in-clan: "&cVocê já está em um clan!"
  not-in-clan: "&cVocê não está em um clan!"
  tag-too-long: "&cA tag deve ter no máximo 4 caracteres!"
  clan-created: "&aClan &e%clan% &acriado com sucesso! Tag: &e%tag%"
  clan-create-failed: "&cFalha ao criar clan!"
  clan-deleted: "&aClan &e%clan% &adeletado com sucesso!"
  clan-delete-failed: "&cFalha ao deletar clan!"
  player-invited: "&aJogador &e%player% &aconvidado com sucesso!"
  clan-invited: "&aVocê foi convidado para o clan &e%clan%&a!"
  left-clan: "&aVocê saiu do clan &e%clan%&a!"
  player-kicked: "&aJogador &e%player% &aexpulso com sucesso!"
  kicked-from-clan: "&cVocê foi expulso do clan &e%clan%&c!"
  leader-cannot-leave: "&cO líder não pode sair do clan! Transfira a liderança primeiro."
  player-already-in-clan: "&cEste jogador já está em um clan!"
  player-not-in-clan: "&cEste jogador não está no seu clan!"
  
  clan-info-header: "&6=== Informações do Clan &e%clan% &6==="
  clan-info-tag: "&7Tag: &e%tag%"
  clan-info-leader: "&7Líder: &e%leader%"
  clan-info-balance: "&7Saldo: &a$%balance%"
  clan-info-kdr: "&7KDR: &e%kills%&7/&c%deaths%"
  clan-members-header: "&6=== Membros do Clan &e%clan% &6==="
  clan-member: "&7- &e%player% &7(%role%)"
  
  deposited-to-clan: "&a$%amount% depositado no clan!"
  deposit-failed: "&cFalha ao depositar no clan!"
  withdrawn-from-clan: "&a$%amount% sacado do clan!"
  withdraw-failed: "&cFalha ao sacar do clan!"
  
  clan-tag-updated: "&aTag do clan atualizada para &e%tag%&a!"
  
  war-declared: "&cGuerra declarada contra o clan &e%clan%&c!"
  cannot-war-self: "&cVocê não pode declarar guerra contra seu próprio clan!"
  
  top-clans-header: "&6=== Top 10 Clans ==="
  top-clan-entry: "&e%position%. &7%clan% &7- &a%kills% kills &7- &eKDR: %kdr%"
  
  home-usage: "&cUso: /home <nome>"
  sethome-usage: "&cUso: /sethome <nome>"
  delhome-usage: "&cUso: /delhome <nome>"
  home-not-found: "&cHome &e%home% &cnão encontrada!"
  home-world-not-found: "&cMundo da home não encontrado!"
  home-set: "&aHome &e%home% &adefinida com sucesso!"
  home-set-failed: "&cFalha ao definir home!"
  home-deleted: "&aHome &e%home% &aremovida com sucesso!"
  max-homes-reached: "&cVocê atingiu o limite de &e%max% &chomes!"
  no-homes: "&cVocê não possui homes!"
  teleported-to-home: "&aTeleportado para a home &e%home%&a!"
  
  homes-gui-title: "&6Suas Homes"
  home-item-name: "&e%home%"
  home-item-world: "&7Mundo: &e%world%"
  home-item-coords: "&7Coordenadas: &e%x%, %y%, %z%"
  home-item-created: "&7Criada em: &e%date%"
  home-item-click: "&aClique para teleportar!"
  
  warp-usage: "&cUso: /warp <nome>"
  setwarp-usage: "&cUso: /setwarp <nome>"
  delwarp-usage: "&cUso: /delwarp <nome>"
  warp-not-found: "&cWarp &e%warp% &cnão encontrado!"
  warp-world-not-found: "&cMundo do warp não encontrado!"
  warp-set: "&aWarp &e%warp% &adefinido com sucesso!"
  warp-set-failed: "&cFalha ao definir warp!"
  warp-deleted: "&aWarp &e%warp% &aremovido com sucesso!"
  warp-delete-failed: "&cFalha ao remover warp!"
  teleported-to-warp: "&aTeleportado para o warp &e%warp%&a!"
  
  tpa-usage: "&cUso: /tpa <jogador>"
  cannot-tpa-self: "&cVocê não pode se teleportar para si mesmo!"
  tpa-pending-request: "&cVocê já possui uma solicitação de teleporte pendente!"
  tpa-sent: "&aSolicitação de teleporte enviada para &e%target%&a!"
  tpa-received: "&e%requester% &asolicitou teleporte para você!"
  tpa-commands: "&7Use &e/tpaccept &7ou &c/tpdeny"
  tpa-success: "&aTeleportado para &e%target%&a!"
  tpa-accepted: "&aTeleporte aceito por &e%requester%&a!"
  tpa-denied: "&cTeleporte negado por &e%target%&c!"
  no-tpa-request: "&cVocê não possui solicitações de teleporte!"
  tpa-accept-failed: "&cFalha ao aceitar teleporte!"
  tpa-deny-failed: "&cFalha ao negar teleporte!"
  tpa-failed: "&cFalha ao enviar solicitação de teleporte!"
