messages:
  only-players: "&c&l[SLYCORE] &cEste comando só pode ser executado por jogadores!"
  go-usage: "&c&l[SLYCORE] &cUso: &e/go <jogador>"
  player-not-found: "&c&l[SLYCORE] &cJogador &e%player% &cnão encontrado!"
  cannot-teleport-self: "&c&l[SLYCORE] &cVocê não pode se teleportar para si mesmo!"
  teleporting-to: "&a&l[SLYCORE] &aTeleportando para &e%player% &ano servidor &b%server%&a..."
  teleporting-to-player: "&a&l[SLYCORE] &aTeleportando para &e%player%&a..."
